// Localization
const i18n = {
    en: {
        title: "Chess Ultimate",
        play: "Play Game",
        whiteTurn: "White's turn",
        blackTurn: "Black's turn",
        whiteCaptured: "White Captured",
        blackCaptured: "Black Captured",
        moveHistory: "Move History",
        white: "White",
        black: "Black",
        check: "Check!",
        checkmate: "Checkmate! {0} wins!",
        stalemate: "Stalemate! The game is a draw.",
        startTimer: "Start Timer",
        pauseTimer: "Pause Timer",
        newGame: "New Game",
        undoMove: "Undo Move",
        redoMove: "Redo Move",
        flipBoard: "Flip Board",
        aiMove: "AI Move",
        whiteTime: "White:",
        blackTime: "Black:",
        promotion: "Choose a piece for promotion",
        settings: "Settings",
        showLabels: "Show board labels",
        boardSize: "Board size",
        animationSpeed: "Animation Speed",
        soundEffects: "Sound Effects",
        close: "Close",
        createdBy: "Created by voxdroid",
        cs_blue: "Blue",
        cs_green: "Green",
        cs_red: "Red",
        cs_purple: "Purple",
        cs_orange: "Orange",
        cs_teal: "Teal",
        cs_pink: "Pink",
        cs_brown: "Brown",
        cs_gray: "Gray",
        cs_blackwhite: "Black & White",
        cs_rainbow: "Rainbow",
        cs_rainbow_soft: "Rainbow-Soft",
        cs_sunset: "Sunset",
        cs_forest: "Forest",
        cs_ocean: "Ocean",
        cs_candy: "Candy",
        cs_galaxy: "Galaxy",
        cs_lava: "Lava",
        cs_ice: "Ice",
        cs_metallic: "Metallic",
        cs_pastel: "Pastel",
        cs_vintage: "Vintage",
        cs_space: "Space",
        ps_unicode: "Unicode",
        ps_classic: "Classic",
        ps_modern: "Modern",
        ps_aesthetic: "Aesthetic",
        ps_pixel: "Pixel",
        ps_3d_BW: "Brown & White 3D",
        ps_2d_BW: "Brown & White 2D"
    },
    es: {
        title: "Ajedrez Definitivo",
        play: "Jugar",
        whiteTurn: "Turno de blancas",
        blackTurn: "Turno de negras",
        whiteCaptured: "Capturadas por Blancas",
        blackCaptured: "Capturadas por Negras",
        moveHistory: "Historial de Movimientos",
        white: "Blancas",
        black: "Negras",
        check: "¡Jaque!",
        checkmate: "¡Jaque mate! {0} gana!",
        stalemate: "¡Tablas! El juego es un empate.",
        startTimer: "Iniciar temporizador",
        pauseTimer: "Pausar temporizador",
        newGame: "Nuevo Juego",
        undoMove: "Deshacer Movimiento",
        redoMove: "Rehacer Movimiento",
        flipBoard: "Voltear Tablero",
        aiMove: "Movimiento de IA",
        whiteTime: "Blancas:",
        blackTime: "Negras:",
        promotion: "Elige una pieza para la promoción",
        settings: "Configuraciones",
        showLabels: "Mostrar etiquetas del tablero",
        boardSize: "Tamaño del tablero",
        animationSpeed: "Velocidad de Animación",
        soundEffects: "Efectos de Sonido",
        close: "Cerrar",
        createdBy: "Creado por voxdroid",
        cs_blue: "Azul",
        cs_green: "Verde",
        cs_red: "Rojo",
        cs_purple: "Púrpura",
        cs_orange: "Naranja",
        cs_teal: "Verde Azulado",
        cs_pink: "Rosa",
        cs_brown: "Marrón",
        cs_gray: "Gris",
        cs_blackwhite: "Blanco y Negro",
        cs_rainbow: "Arcoíris",
        cs_rainbow_soft: "Arcoíris Suave",
        cs_sunset: "Atardecer",
        cs_forest: "Bosque",
        cs_ocean: "Océano",
        cs_candy: "Dulce",
        cs_galaxy: "Galaxia",
        cs_lava: "Lava",
        cs_ice: "Hielo",
        cs_metallic: "Metálico",
        cs_pastel: "Pastel",
        cs_vintage: "Vintage",
        cs_space: "Espacio",
        ps_unicode: "Unicode",
        ps_classic: "Clásico",
        ps_modern: "Moderno",
        ps_aesthetic: "Estético",
        ps_pixel: "Pixel",
        ps_3d_BW: "Marrón y Blanco 3D",
        ps_2d_BW: "Marrón y Blanco 2D"
    },
    fr: {
        title: "Échecs Ultime",
        play: "Jouer",
        whiteTurn: "Tour des blancs",
        blackTurn: "Tour des noirs",
        whiteCaptured: "Pièces capturées par les Blancs",
        blackCaptured: "Pièces capturées par les Noirs",
        moveHistory: "Historique des coups",
        white: "Blancs",
        black: "Noirs",
        check: "Échec!",
        checkmate: "Échec et mat! {0} gagne!",
        stalemate: "Pat! Le jeu est nul.",
        startTimer: "Démarrer le chronomètre",
        pauseTimer: "Pause chronomètre",
        newGame: "Nouvelle Partie",
        undoMove: "Annuler le coup",
        redoMove: "Refaire le coup",
        flipBoard: "Retourner l'échiquier",
        aiMove: "Coup de l'IA",
        whiteTime: "Blancs:",
        blackTime: "Noirs:",
        promotion: "Choisissez une pièce pour la promotion",
        settings: "Paramètres",
        showLabels: "Afficher les étiquettes de l'échiquier",
        boardSize: "Taille de l'échiquier",
        animationSpeed: "Vitesse d'animation",
        soundEffects: "Effets sonores",
        close: "Fermer",
        createdBy: "Créé par voxdroid",
        cs_blue: "Bleu",
        cs_green: "Vert",
        cs_red: "Rouge",
        cs_purple: "Violet",
        cs_orange: "Orange",
        cs_teal: "Sarcelle",
        cs_pink: "Rose",
        cs_brown: "Marron",
        cs_gray: "Gris",
        cs_blackwhite: "Noir et Blanc",
        cs_rainbow: "Arc-en-ciel",
        cs_rainbow_soft: "Arc-en-ciel Doux",
        cs_sunset: "Coucher de Soleil",
        cs_forest: "Forêt",
        cs_ocean: "Océan",
        cs_candy: "Bonbon",
        cs_galaxy: "Galaxie",
        cs_lava: "Lave",
        cs_ice: "Glace",
        cs_metallic: "Métallique",
        cs_pastel: "Pastel",
        cs_vintage: "Vintage",
        cs_space: "Espace",
        ps_unicode: "Unicode",
        ps_classic: "Classique",
        ps_modern: "Moderne",
        ps_aesthetic: "Esthétique",
        ps_pixel: "Pixel",
        ps_3d_BW: "Marron et Blanc 3D",
        ps_2d_BW: "Marron et Blanc 2D"
    },
    de: {
        title: "Schach Ultimativ",
        play: "Spiel starten",
        whiteTurn: "Weiß ist am Zug",
        blackTurn: "Schwarz ist am Zug",
        whiteCaptured: "Geschlagene weiße Figuren",
        blackCaptured: "Geschlagene schwarze Figuren",
        moveHistory: "Zughistorie",
        white: "Weiß",
        black: "Schwarz",
        check: "Schach!",
        checkmate: "Schachmatt! {0} gewinnt!",
        stalemate: "Patt! Das Spiel endet unentschieden.",
        startTimer: "Timer starten",
        pauseTimer: "Timer pausieren",
        newGame: "Neues Spiel",
        undoMove: "Zug rückgängig machen",
        redoMove: "Zug wiederholen",
        flipBoard: "Brett drehen",
        aiMove: "KI-Zug",
        whiteTime: "Weiß:",
        blackTime: "Schwarz:",
        promotion: "Wählen Sie eine Figur zur Beförderung",
        settings: "Einstellungen",
        showLabels: "Brettbeschriftungen anzeigen",
        boardSize: "Brettgröße",
        animationSpeed: "Animationsgeschwindigkeit",
        soundEffects: "Soundeffekte",
        close: "Schließen",
        createdBy: "Erstellt von voxdroid",
        cs_blue: "Blau",
        cs_green: "Grün",
        cs_red: "Rot",
        cs_purple: "Lila",
        cs_orange: "Orange",
        cs_teal: "Türkis",
        cs_pink: "Rosa",
        cs_brown: "Braun",
        cs_gray: "Grau",
        cs_blackwhite: "Schwarz-Weiß",
        cs_rainbow: "Regenbogen",
        cs_rainbow_soft: "Weicher Regenbogen",
        cs_sunset: "Sonnenuntergang",
        cs_forest: "Wald",
        cs_ocean: "Ozean",
        cs_candy: "Süßigkeit",
        cs_galaxy: "Galaxie",
        cs_lava: "Lava",
        cs_ice: "Eis",
        cs_metallic: "Metallisch",
        cs_pastel: "Pastell",
        cs_vintage: "Vintage",
        cs_space: "Weltraum",
        ps_unicode: "Unicode",
        ps_classic: "Klassisch",
        ps_modern: "Modern",
        ps_aesthetic: "Ästhetisch",
        ps_pixel: "Pixel",
        ps_3d_BW: "Braun-Weiß 3D",
        ps_2d_BW: "Braun-Weiß 2D"
    },
    ja: {
        title: "チェスアルティメット",
        play: "ゲームをプレイ",
        whiteTurn: "白のターン",
        blackTurn: "黒のターン",
        whiteCaptured: "白の捕獲駒",
        blackCaptured: "黒の捕獲駒",
        moveHistory: "手順",
        white: "白",
        black: "黒",
        check: "チェック！",
        checkmate: "チェックメイト！{0}の勝ち！",
        stalemate: "ステイルメイト！引き分けです。",
        startTimer: "タイマー開始",
        pauseTimer: "タイマーポーズ",
        newGame: "新しいゲーム",
        undoMove: "手を戻す",
        redoMove: "手をやり直す",
        flipBoard: "ボードを反転",
        aiMove: "AIの手",
        whiteTime: "白:",
        blackTime: "黒:",
        promotion: "昇格する駒を選んでください",
        settings: "設定",
        showLabels: "ボードラベルを表示",
        boardSize: "ボードサイズ",
        animationSpeed: "アニメーション速度",
        soundEffects: "効果音",
        close: "閉じる",
        createdBy: "voxdroidによって作成された",
        cs_blue: "青",
        cs_green: "緑",
        cs_red: "赤",
        cs_purple: "紫",
        cs_orange: "オレンジ",
        cs_teal: "ティール",
        cs_pink: "ピンク",
        cs_brown: "茶色",
        cs_gray: "灰色",
        cs_blackwhite: "白黒",
        cs_rainbow: "虹",
        cs_rainbow_soft: "ソフト虹",
        cs_sunset: "夕日",
        cs_forest: "森",
        cs_ocean: "海",
        cs_candy: "キャンディ",
        cs_galaxy: "銀河",
        cs_lava: "溶岩",
        cs_ice: "氷",
        cs_metallic: "メタリック",
        cs_pastel: "パステル",
        cs_vintage: "ビンテージ",
        cs_space: "宇宙",
        ps_unicode: "ユニコード",
        ps_classic: "クラシック",
        ps_modern: "モダン",
        ps_aesthetic: "美的",
        ps_pixel: "ピクセル",
        ps_3d_BW: "茶色と白 3D",
        ps_2d_BW: "茶色と白 2D"
    },
    ko: {
        title: "체스 얼티밋",
        play: "게임 시작",
        whiteTurn: "백의 차례",
        blackTurn: "흑의 차례",
        whiteCaptured: "백이 잡은 말",
        blackCaptured: "흑이 잡은 말",
        moveHistory: "수순",
        white: "백",
        black: "흑",
        check: "체크!",
        checkmate: "체크메이트! {0} 승리!",
        stalemate: "스테일메이트! 게임은 무승부입니다.",
        startTimer: "타이머 시작",
        pauseTimer: "타이머 일시 정지",
        newGame: "새 게임",
        undoMove: "이전 수로 돌아가기",
        redoMove: "다시 실행",
        flipBoard: "보드 뒤집기",
        aiMove: "AI 움직임",
        whiteTime: "백:",
        blackTime: "흑:",
        promotion: "승격할 기물을 선택하세요",
        settings: "설정",
        showLabels: "보드 라벨 표시",
        boardSize: "보드 크기",
        animationSpeed: "애니메이션 속도",
        soundEffects: "사운드 효과",
        close: "닫기",
        createdBy: "voxdroid 제작",
        cs_blue: "파란색",
        cs_green: "초록색",
        cs_red: "빨간색",
        cs_purple: "보라색",
        cs_orange: "주황색",
        cs_teal: "청록색",
        cs_pink: "분홍색",
        cs_brown: "갈색",
        cs_gray: "회색",
        cs_blackwhite: "검정과 흰색",
        cs_rainbow: "무지개",
        cs_rainbow_soft: "부드러운 무지개",
        cs_sunset: "노을",
        cs_forest: "숲",
        cs_ocean: "바다",
        cs_candy: "캔디",
        cs_galaxy: "은하",
        cs_lava: "용암",
        cs_ice: "얼음",
        cs_metallic: "금속",
        cs_pastel: "파스텔",
        cs_vintage: "빈티지",
        cs_space: "우주",
        ps_unicode: "유니코드",
        ps_classic: "클래식",
        ps_modern: "모던",
        ps_aesthetic: "미적",
        ps_pixel: "픽셀",
        ps_3d_BW: "갈색과 흰색 3D",
        ps_2d_BW: "갈색과 흰색 2D"
    },
    zh: {
        title: "国际象棋终极版",
        play: "开始游戏",
        whiteTurn: "白方回合",
        blackTurn: "黑方回合",
        whiteCaptured: "白方吃子",
        blackCaptured: "黑方吃子",
        moveHistory: "行棋记录",
        white: "白方",
        black: "黑方",
        check: "将军！",
        checkmate: "将死！{0}赢了！",
        stalemate: "僵局！比赛平局。",
        startTimer: "启动计时器",
        pauseTimer: "暂停计时器",
        newGame: "新游戏",
        undoMove: "撤销移动",
        redoMove: "重做移动",
        flipBoard: "翻转棋盘",
        aiMove: "AI 移动",
        whiteTime: "白方:",
        blackTime: "黑方:",
        promotion: "选择升变的棋子",
        settings: "设置",
        showLabels: "显示棋盘标签",
        boardSize: "棋盘大小",
        animationSpeed: "动画速度",
        soundEffects: "音效",
        close: "关闭",
        createdBy: "由 voxdroid 创建",
        cs_blue: "蓝色",
        cs_green: "绿色",
        cs_red: "红色",
        cs_purple: "紫色",
        cs_orange: "橙色",
        cs_teal: "青色",
        cs_pink: "粉红色",
        cs_brown: "棕色",
        cs_gray: "灰色",
        cs_blackwhite: "黑白",
        cs_rainbow: "彩虹",
        cs_rainbow_soft: "柔彩虹",
        cs_sunset: "日落",
        cs_forest: "森林",
        cs_ocean: "海洋",
        cs_candy: "糖果",
        cs_galaxy: "银河",
        cs_lava: "熔岩",
        cs_ice: "冰",
        cs_metallic: "金属",
        cs_pastel: "柔和色",
        cs_vintage: "复古",
        cs_space: "太空",
        ps_unicode: "Unicode",
        ps_classic: "经典",
        ps_modern: "现代",
        ps_aesthetic: "美学",
        ps_pixel: "像素",
        ps_3d_BW: "棕白 3D",
        ps_2d_BW: "棕白 2D"
    }
};

let currentLanguage = 'en';